sudo: false
language: go
go:
  - 1.7
  - 1.8
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
branches:
 only:
  - master
before_install:
  - cd $GOPATH/src/github.com/pjgg/Go-Option
  - go get -t -v ./...
install: 
  - go build -v -ldflags "-X main.version=$TRAVIS_TAG -s -w" -o bin/option-$TRAVIS_TAG ./option
script: 
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./option
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
  - pablo.gonzalez.granados@gmail.com
